name: DeluxeTags
main: me.clip.deluxetags.DeluxeTags
version: 1.0
author: extended_clip
description: DeluxeChat add on to display a selectable prefix
softdepend: [DeluxeChat]
commands:
   tags:
     description: DeluxeTags command
permissions:
    deluxetags.reload:
        description: ability to reload the plugin
        default: op
    deluxetags.list:
        description: ability to view own wins
        default: op
    deluxetags.set:
        description: ability to view others wins
        default: op