name: DeluxeTags
main: me.clip.deluxetags.DeluxeTags
version: 1.0
author: extended_clip
description: DeluxeChat addon to display a selectable prefix
commands:
   tags:
     description: ChatReaction commands
permissions:
    deluxetags.reload:
        description: ability to reload the plugin
        default: op
    deluxetags.list:
        description: ability to view own wins
        default: op
    deluxetags.set:
        description: ability to view others wins
        default: op